services:
  signalk:
#    build: .
    image: signalk/signalk-server
    container_name: signalk
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - signalk-data:/home/node/.signalk
      - ./:/home/node/.signalk/node_modules/signalk-rtsp-plugin
      - /media/psf/DebianDev/signalk-container:/home/node/.signalk/node_modules/signalk-container
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - signalk-net

volumes:
  signalk-data:

networks:
  signalk-net:
